[project]
name = "etl-testing-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tamalero",
]

[tool.uv.sources]
tamalero = { path="module_test_sw/", editable=true }
