Arduino:
  baud: 115200
  port: "/dev/arduino"
  timeout: 1

KCU:
  IP: 192.168.0.15
  fw_version: 3.2.3
  port: "/dev/kcu_uart"

Chiller:
  baud: #insert
  port: "/dev/chiller"
  timeout: 1

HV:
  baud: 9600
  port: "/dev/hv_supply"
  timeout: 1
  board_addr: 0
  channel: 0
  volt_tolerance: .5
  current_limit: 100 # microamps
  ramp_up: 2 # volts/second
  ramp_down: 2 # volts/second